// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tweets.sql

package database

import (
	"context"
	"time"
)

const insertTweet = `-- name: InsertTweet :exec
INSERT INTO tweets
(
  tweet_id,
  created_at,
  full_text,
  possibly_sensitive,
  retweeted
) VALUES (
  $1, $2, $3, $4, $5
  )
RETURNING tweet_id, created_at, full_text, possibly_sensitive, retweeted
`

type InsertTweetParams struct {
	TweetID           string
	CreatedAt         time.Time
	FullText          string
	PossiblySensitive bool
	Retweeted         bool
}

func (q *Queries) InsertTweet(ctx context.Context, arg InsertTweetParams) error {
	_, err := q.db.ExecContext(ctx, insertTweet,
		arg.TweetID,
		arg.CreatedAt,
		arg.FullText,
		arg.PossiblySensitive,
		arg.Retweeted,
	)
	return err
}
