// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tweets.sql

package database

import (
	"context"
	"time"
)

const getTweets = `-- name: GetTweets :many
select full_text, url, retweeted
from tweets
`

type GetTweetsRow struct {
	FullText  string
	Url       string
	Retweeted bool
}

func (q *Queries) GetTweets(ctx context.Context) ([]GetTweetsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTweets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTweetsRow
	for rows.Next() {
		var i GetTweetsRow
		if err := rows.Scan(&i.FullText, &i.Url, &i.Retweeted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTweet = `-- name: InsertTweet :exec
INSERT INTO tweets
(
  tweet_id,
  created_at,
  full_text,
  possibly_sensitive,
  retweeted,
  url
) VALUES (
  $1, $2, $3, $4, $5, $6
  )
  ON CONFLICT (tweet_id) DO NOTHING
RETURNING tweet_id, created_at, full_text, possibly_sensitive, retweeted, url
`

type InsertTweetParams struct {
	TweetID           string
	CreatedAt         time.Time
	FullText          string
	PossiblySensitive bool
	Retweeted         bool
	Url               string
}

func (q *Queries) InsertTweet(ctx context.Context, arg InsertTweetParams) error {
	_, err := q.db.ExecContext(ctx, insertTweet,
		arg.TweetID,
		arg.CreatedAt,
		arg.FullText,
		arg.PossiblySensitive,
		arg.Retweeted,
		arg.Url,
	)
	return err
}
